spring.shardingsphere.datasource.names= ds0

spring.shardingsphere.datasource.ds0.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds0.url=jdbc:mysql://localhost:3306/test_sharding0
spring.shardingsphere.datasource.ds0.password=123456
spring.shardingsphere.datasource.ds0.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds0.username=root

#spring.shardingsphere.datasource.ds1.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.shardingsphere.datasource.ds1.url=jdbc:mysql://localhost:3306/test_sharding1
#spring.shardingsphere.datasource.ds1.password=123456
#spring.shardingsphere.datasource.ds1.type=com.alibaba.druid.pool.DruidDataSource
#spring.shardingsphere.datasource.ds1.username=root



#spring.shardingsphere.sharding.tables.reviews.actual-data-nodes=ds0.reviews-sharding-$->{0..1}
#
#spring.shardingsphere.sharding.tables.reviews.table-strategy.inline.sharding-column=id
#spring.shardingsphere.sharding.tables.reviews.table-strategy.inline.algorithm-expression= reviews-sharding-$->{id % 2}
#
#spring.shardingsphere.sharding.tables.reviews.key-generator.type=SNOWFLAKE
#spring.shardingsphere.sharding.tables.reviews.key-generator.column=id
#spring.shardingsphere.sharding.tables.reviews.key-generator.props.worker-id:1

#spring.shardingsphere.props.sql.show=true

spring.main.allow-bean-definition-overriding=true